local T = require('tests.lib.t')
dofile(ROOT .. '/shared/pending.lua')

T.describe('Pending', function()
    T.it('allows one action per key', function()
        local p = Pending.new()
        T.eq(p:start(7, 'a', 0, 1000), 1)
        T.eq({ p:start(7, 'b', 0, 1000) }, { nil, 'busy' })
        T.eq(p:start(8, 'c', 0, 1000), 2, 'other key')
    end)

    T.it('finishes only after the duration and only once', function()
        local p = Pending.new()
        local id = p:start(7, 'latte', 1000, 5000)
        T.eq({ p:finish(7, id, 3000) }, { nil, 'too_early' })
        T.eq(p:finish(7, id, 6000), 'latte')
        T.eq({ p:finish(7, id, 6000) }, { nil, 'none' }, 'second finish')
    end)

    T.it('keeps the action when finished too early', function()
        local p = Pending.new()
        local id = p:start(7, 'latte', 0, 5000)
        p:finish(7, id, 100)
        T.eq(p:finish(7, id, 5000), 'latte')
    end)

    T.it('accepts a small timing tolerance', function()
        local p = Pending.new()
        local id = p:start(7, 'latte', 0, 5000)
        T.eq(p:finish(7, id, 4400, 750), 'latte')
    end)

    T.it('rejects a wrong id', function()
        local p = Pending.new()
        local id = p:start(7, 'latte', 0, 0)
        T.eq({ p:finish(7, id + 1, 10) }, { nil, 'none' })
        T.eq({ p:finish(9, id, 10) }, { nil, 'none' }, 'other key')
    end)

    T.it('returns expired data once so it can be refunded', function()
        local p = Pending.new()
        local id = p:start(7, 'bill', 0, 0, 60000)
        T.eq({ p:finish(7, id, 70000) }, { nil, 'expired', 'bill' })
        T.eq({ p:finish(7, id, 70000) }, { nil, 'none' })
    end)

    T.it('cancel returns the data once', function()
        local p = Pending.new()
        p:start(7, 'latte', 0, 5000)
        T.eq(p:cancel(7), 'latte')
        T.eq(p:cancel(7), nil)
        T.eq(p:start(7, 'next', 0, 1), 2, 'key free again')
    end)

    T.it('get returns data and id without removing', function()
        local p = Pending.new()
        local id = p:start(7, 'latte', 0, 5000)
        T.eq({ p:get(7) }, { 'latte', id })
        T.eq({ p:get(8) }, {})
    end)

    T.it('expire removes and returns only expired actions', function()
        local p = Pending.new()
        p:start(1, 'old', 0, 0, 1000)
        p:start(2, 'fresh', 0, 0, 90000)
        p:start(3, 'forever', 0, 0)
        T.eq(p:expire(5000), { { key = 1, data = 'old' } })
        T.eq(p:get(2), 'fresh')
        T.eq(p:get(3), 'forever')
    end)

    T.it('each visits every open action', function()
        local p = Pending.new()
        p:start(1, 'a', 0, 0)
        p:start(2, 'b', 0, 0)
        local seen = {}
        p:each(function(key, data) seen[key] = data end)
        T.eq(seen, { 'a', 'b' })
    end)
end)
