local T = require('tests.lib.t')
dofile(ROOT .. '/shared/rules.lua')

T.describe('Rules.wholeNumber', function()
    T.it('accepts whole numbers inside the range', function()
        T.eq(Rules.wholeNumber(5, 1, 10), 5)
        T.eq(Rules.wholeNumber(1, 1, 10), 1)
        T.eq(Rules.wholeNumber(10, 1, 10), 10)
        T.eq(Rules.wholeNumber(4.0, 1, 10), 4)
    end)
    T.it('rejects anything else', function()
        T.eq(Rules.wholeNumber(0, 1, 10), nil, 'below')
        T.eq(Rules.wholeNumber(11, 1, 10), nil, 'above')
        T.eq(Rules.wholeNumber(-3, 1, 10), nil, 'negative')
        T.eq(Rules.wholeNumber(2.5, 1, 10), nil, 'fraction')
        T.eq(Rules.wholeNumber('5', 1, 10), nil, 'string')
        T.eq(Rules.wholeNumber(0 / 0, 1, 10), nil, 'NaN')
        T.eq(Rules.wholeNumber(math.huge, 1, math.huge), nil, 'infinity')
        T.eq(Rules.wholeNumber(1e300, 1, 10), nil, 'huge')
        T.eq(Rules.wholeNumber(nil, 1, 10), nil, 'nil')
        T.eq(Rules.wholeNumber({}, 1, 10), nil, 'table')
    end)
end)

T.describe('Rules.cleanText', function()
    T.it('trims and keeps normal text', function()
        T.eq(Rules.cleanText('  Cat Café  ', 40), 'Cat Café')
    end)
    T.it('turns control characters into spaces', function()
        T.eq(Rules.cleanText('a\nb\tc', 40), 'a b c')
    end)
    T.it('cuts to the character limit without splitting a character', function()
        T.eq(Rules.cleanText('ééééé', 3), 'ééé')
        T.eq(Rules.cleanText('abcdef', 4), 'abcd')
    end)
    T.it('drops bytes that are not valid UTF-8', function()
        T.eq(Rules.cleanText('ab\255cd', 10), 'abcd')
    end)
    T.it('returns nil for empty or non-text input', function()
        T.eq(Rules.cleanText('   ', 10), nil)
        T.eq(Rules.cleanText(nil, 10), nil)
        T.eq(Rules.cleanText(42, 10), nil)
    end)
end)

T.describe('Rules.coords', function()
    T.it('accepts finite coordinates inside the map', function()
        T.eq(Rules.coords({ x = 1.5, y = -2, z = 30 }), { x = 1.5, y = -2.0, z = 30.0 })
    end)
    T.it('rejects missing, non-number, NaN and far-away values', function()
        T.eq(Rules.coords(nil), nil)
        T.eq(Rules.coords({ x = 1, y = 2 }), nil)
        T.eq(Rules.coords({ x = '1', y = 2, z = 3 }), nil)
        T.eq(Rules.coords({ x = 0 / 0, y = 2, z = 3 }), nil)
        T.eq(Rules.coords({ x = 1, y = 2, z = math.huge }), nil)
        T.eq(Rules.coords({ x = 99999, y = 2, z = 3 }), nil)
    end)
end)

T.describe('Rules.heading', function()
    T.it('wraps any finite number into 0-360', function()
        T.eq(Rules.heading(370), 10.0)
        T.eq(Rules.heading(-90), 270.0)
    end)
    T.it('rejects non-numbers', function()
        T.eq(Rules.heading('90'), nil)
        T.eq(Rules.heading(0 / 0), nil)
    end)
end)

local PERMS = {
    [1] = { cook = true },
    [3] = { cook = true, hire = true },
}

T.describe('rank rules', function()
    T.it('can() reads the rank permission table', function()
        T.eq(Rules.can(PERMS, 1, 'cook'), true)
        T.eq(Rules.can(PERMS, 1, 'hire'), false)
        T.eq(Rules.can(PERMS, 2, 'cook'), false, 'rank without an entry')
        T.eq(Rules.can(PERMS, nil, 'cook'), false)
    end)
    T.it('canManage() needs a strictly higher rank', function()
        T.eq(Rules.canManage(3, 2), true)
        T.eq(Rules.canManage(3, 3), false)
        T.eq(Rules.canManage(2, 3), false)
        T.eq(Rules.canManage(nil, 1), false)
        T.eq(Rules.canManage(3, nil), false)
    end)
    T.it('canAssignRank() allows ranks below yours and never Owner', function()
        T.eq(Rules.canAssignRank(3, 1), true)
        T.eq(Rules.canAssignRank(3, 2), true)
        T.eq(Rules.canAssignRank(3, 3), false, 'own rank')
        T.eq(Rules.canAssignRank(4, 3), true)
        T.eq(Rules.canAssignRank(4, 4), false, 'owner')
        T.eq(Rules.canAssignRank(4, 0), false, 'zero')
        T.eq(Rules.canAssignRank(4, nil), false)
    end)
end)

T.describe('Rules.missingIngredients', function()
    local latte = { coffee_beans = 1, milk = 2 }
    T.it('is empty when there is enough for the quantity', function()
        T.eq(Rules.missingIngredients(latte, 2, { coffee_beans = 2, milk = 4 }), {})
    end)
    T.it('lists every short ingredient, sorted', function()
        T.eq(Rules.missingIngredients(latte, 3, { coffee_beans = 1 }), {
            { item = 'coffee_beans', need = 3, have = 1 },
            { item = 'milk', need = 6, have = 0 },
        })
    end)
end)

local CATALOG = {
    { item = 'milk', label = 'Milk', price = 20, pack = 10 },
    { item = 'ice', label = 'Ice', price = 10, pack = 20 },
}

T.describe('Rules.cartTotal', function()
    T.it('adds up a valid cart', function()
        local total, lines = Rules.cartTotal(CATALOG, { { item = 'milk', packs = 2 }, { item = 'ice', packs = 1 } }, 50)
        T.eq(total, 50)
        T.eq(lines, {
            { item = 'milk', packs = 2, amount = 20, cost = 40 },
            { item = 'ice', packs = 1, amount = 20, cost = 10 },
        })
    end)
    T.it('rejects empty, unknown, repeated and bad pack counts', function()
        T.eq(select(2, Rules.cartTotal(CATALOG, {}, 50)), 'The cart is empty')
        T.eq(select(2, Rules.cartTotal(CATALOG, nil, 50)), 'The cart is empty')
        T.eq(select(2, Rules.cartTotal(CATALOG, { { item = 'gold', packs = 1 } }, 50)), 'Unknown item in the cart')
        T.eq(select(2, Rules.cartTotal(CATALOG, { 'milk' }, 50)), 'Unknown item in the cart')
        T.eq(select(2, Rules.cartTotal(CATALOG, { { item = 'milk', packs = 1 }, { item = 'milk', packs = 1 } }, 50)), 'Milk is listed twice')
        T.eq(select(2, Rules.cartTotal(CATALOG, { { item = 'milk', packs = 0 } }, 50)), 'Pick 1-50 packs of Milk')
        T.eq(select(2, Rules.cartTotal(CATALOG, { { item = 'milk', packs = 51 } }, 50)), 'Pick 1-50 packs of Milk')
        T.eq(select(2, Rules.cartTotal(CATALOG, { { item = 'milk', packs = 1.5 } }, 50)), 'Pick 1-50 packs of Milk')
    end)
end)

T.describe('Rules.splitBill', function()
    T.it('gives the employee their commission, rounded down', function()
        T.eq({ Rules.splitBill(100, 10) }, { 90, 10 })
        T.eq({ Rules.splitBill(15, 10) }, { 14, 1 })
        T.eq({ Rules.splitBill(5, 0) }, { 5, 0 })
    end)
end)

T.describe('Rules.paycheckFor', function()
    local AMOUNTS = { [1] = 150, [2] = 250, [3] = 400, [4] = 600 }
    T.it('returns the amount for the rank', function()
        T.eq(Rules.paycheckFor(AMOUNTS, 1), 150)
        T.eq(Rules.paycheckFor(AMOUNTS, 4), 600)
    end)
    T.it('pays nothing for unknown ranks or bad config values', function()
        T.eq(Rules.paycheckFor(AMOUNTS, 5), 0)
        T.eq(Rules.paycheckFor(AMOUNTS, nil), 0)
        T.eq(Rules.paycheckFor({ [1] = -50 }, 1), 0, 'negative')
        T.eq(Rules.paycheckFor({ [1] = 99.5 }, 1), 0, 'fraction')
        T.eq(Rules.paycheckFor({ [1] = '100' }, 1), 0, 'string')
        T.eq(Rules.paycheckFor(nil, 1), 0, 'no table')
    end)
end)

T.describe('Rules.cookTime', function()
    T.it('multiplies the recipe time by the quantity', function()
        T.eq(Rules.cookTime({ time = 4000 }, 3), 12000)
    end)
end)
