-- Vanguard Business items for ox_inventory (Qbox / ESX).
-- Paste everything between the braces into ox_inventory/data/items.lua, inside its "return {" table,
-- and copy vanguard-business/images/*.png into ox_inventory/web/images/.
-- Generated by tools/gen-ox-items.js - edit shared/types.lua and run "npm run ox-items" instead of editing this file.
return {
    -- Vanguard Business ingredients
    ['beef_patty'] = { label = 'Beef Patty', weight = 150, stack = true, close = true, client = { image = 'vb_beef_patty.png' } },
    ['burger_bun'] = { label = 'Burger Bun', weight = 80, stack = true, close = true, client = { image = 'vb_burger_bun.png' } },
    ['butter'] = { label = 'Butter', weight = 100, stack = true, close = true, client = { image = 'vb_butter.png' } },
    ['cheese'] = { label = 'Cheese', weight = 100, stack = true, close = true, client = { image = 'vb_cheese.png' } },
    ['cocoa'] = { label = 'Cocoa Powder', weight = 100, stack = true, close = true, client = { image = 'vb_cocoa.png' } },
    ['coffee_beans'] = { label = 'Coffee Beans', weight = 100, stack = true, close = true, client = { image = 'vb_coffee_beans.png' } },
    ['eggs'] = { label = 'Eggs', weight = 60, stack = true, close = true, client = { image = 'vb_eggs.png' } },
    ['flour'] = { label = 'Flour', weight = 200, stack = true, close = true, client = { image = 'vb_flour.png' } },
    ['honey'] = { label = 'Honey', weight = 150, stack = true, close = true, client = { image = 'vb_honey.png' } },
    ['ice'] = { label = 'Ice', weight = 100, stack = true, close = true, client = { image = 'vb_ice.png' } },
    ['lemon'] = { label = 'Lemon', weight = 80, stack = true, close = true, client = { image = 'vb_lemon.png' } },
    ['lettuce'] = { label = 'Lettuce', weight = 100, stack = true, close = true, client = { image = 'vb_lettuce.png' } },
    ['malt'] = { label = 'Brewing Malt', weight = 200, stack = true, close = true, client = { image = 'vb_malt.png' } },
    ['milk'] = { label = 'Milk', weight = 250, stack = true, close = true, client = { image = 'vb_milk.png' } },
    ['pepperoni'] = { label = 'Pepperoni', weight = 100, stack = true, close = true, client = { image = 'vb_pepperoni.png' } },
    ['pizza_dough'] = { label = 'Pizza Dough', weight = 250, stack = true, close = true, client = { image = 'vb_pizza_dough.png' } },
    ['potato'] = { label = 'Potato', weight = 150, stack = true, close = true, client = { image = 'vb_potato.png' } },
    ['soda_syrup'] = { label = 'Soda Syrup', weight = 200, stack = true, close = true, client = { image = 'vb_soda_syrup.png' } },
    ['strawberry'] = { label = 'Strawberries', weight = 80, stack = true, close = true, client = { image = 'vb_strawberry.png' } },
    ['tea_leaves'] = { label = 'Tea Leaves', weight = 50, stack = true, close = true, client = { image = 'vb_tea_leaves.png' } },
    ['tomato'] = { label = 'Tomato', weight = 100, stack = true, close = true, client = { image = 'vb_tomato.png' } },

    -- Vanguard Business food and drink
    ['cappuccino'] = {
        label = 'Cappuccino', weight = 250, stack = true, close = true,
        client = {
            image = 'vb_cappuccino.png',
            status = { thirst = 300000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['cheese_toastie'] = {
        label = 'Cheese Toastie', weight = 200, stack = true, close = true,
        client = {
            image = 'vb_cheese_toastie.png',
            status = { hunger = 350000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_sandwich_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['cheeseburger'] = {
        label = 'Cheeseburger', weight = 300, stack = true, close = true,
        client = {
            image = 'vb_cheeseburger.png',
            status = { hunger = 450000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_cs_burger_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['classic_burger'] = {
        label = 'Classic Burger', weight = 320, stack = true, close = true,
        client = {
            image = 'vb_classic_burger.png',
            status = { hunger = 700000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_cs_burger_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['cola'] = {
        label = 'Cola', weight = 350, stack = true, close = true,
        client = {
            image = 'vb_cola.png',
            status = { thirst = 350000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['cookie'] = {
        label = 'Cookie', weight = 60, stack = true, close = true,
        client = {
            image = 'vb_cookie.png',
            status = { hunger = 150000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_amb_donut`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['croissant'] = {
        label = 'Croissant', weight = 100, stack = true, close = true,
        client = {
            image = 'vb_croissant.png',
            status = { hunger = 250000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_sandwich_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['cupcake'] = {
        label = 'Cupcake', weight = 100, stack = true, close = true,
        client = {
            image = 'vb_cupcake.png',
            status = { hunger = 200000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_amb_donut`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['donut'] = {
        label = 'Donut', weight = 100, stack = true, close = true,
        client = {
            image = 'vb_donut.png',
            status = { hunger = 200000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_amb_donut`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['espresso'] = {
        label = 'Espresso', weight = 150, stack = true, close = true,
        client = {
            image = 'vb_espresso.png',
            status = { thirst = 200000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['fries'] = {
        label = 'Fries', weight = 150, stack = true, close = true,
        client = {
            image = 'vb_fries.png',
            status = { hunger = 250000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_food_bs_chips`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['garlic_bread'] = {
        label = 'Garlic Bread', weight = 150, stack = true, close = true,
        client = {
            image = 'vb_garlic_bread.png',
            status = { hunger = 200000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_sandwich_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['green_tea'] = {
        label = 'Green Tea', weight = 250, stack = true, close = true,
        client = {
            image = 'vb_green_tea.png',
            status = { thirst = 400000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['hot_chocolate'] = {
        label = 'Hot Chocolate', weight = 250, stack = true, close = true,
        client = {
            image = 'vb_hot_chocolate.png',
            status = { hunger = 50000, thirst = 350000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['iced_tea'] = {
        label = 'Iced Tea', weight = 350, stack = true, close = true,
        client = {
            image = 'vb_iced_tea.png',
            status = { thirst = 1000000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['kitty_latte'] = {
        label = 'Kitty Latte', weight = 250, stack = true, close = true,
        client = {
            image = 'vb_kitty_latte.png',
            status = { hunger = 50000, thirst = 450000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['latte'] = {
        label = 'Latte', weight = 250, stack = true, close = true,
        client = {
            image = 'vb_latte.png',
            status = { thirst = 350000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['lemonade'] = {
        label = 'Lemonade', weight = 350, stack = true, close = true,
        client = {
            image = 'vb_lemonade.png',
            status = { thirst = 1000000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['neko_cake'] = {
        label = 'Neko Cake', weight = 300, stack = true, close = true,
        client = {
            image = 'vb_neko_cake.png',
            status = { hunger = 500000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_amb_donut`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['pint_beer'] = {
        label = 'Pint of Beer', weight = 500, stack = true, close = true,
        client = {
            image = 'vb_pint_beer.png',
            status = { thirst = 300000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_amb_beer_bottle`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['pizza_margherita'] = {
        label = 'Pizza Margherita', weight = 400, stack = true, close = true,
        client = {
            image = 'vb_pizza_margherita.png',
            status = { hunger = 600000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_sandwich_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['pizza_pepperoni'] = {
        label = 'Pepperoni Pizza', weight = 420, stack = true, close = true,
        client = {
            image = 'vb_pizza_pepperoni.png',
            status = { hunger = 1000000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_sandwich_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['side_salad'] = {
        label = 'Side Salad', weight = 150, stack = true, close = true,
        client = {
            image = 'vb_side_salad.png',
            status = { hunger = 150000, thirst = 50000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_sandwich_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['strawberry_cake'] = {
        label = 'Strawberry Cake', weight = 400, stack = true, close = true,
        client = {
            image = 'vb_strawberry_cake.png',
            status = { hunger = 1000000 },
            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },
            prop = { model = `prop_sandwich_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['strawberry_shake'] = {
        label = 'Strawberry Shake', weight = 300, stack = true, close = true,
        client = {
            image = 'vb_strawberry_shake.png',
            status = { hunger = 200000, thirst = 600000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
    ['virgin_mojito'] = {
        label = 'Virgin Mojito', weight = 350, stack = true, close = true,
        client = {
            image = 'vb_virgin_mojito.png',
            status = { thirst = 500000 },
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `p_amb_coffeecup_01`, pos = vec3(0.02, 0.02, -0.02), rot = vec3(0.0, 0.0, 0.0) },
            usetime = 5000,
        },
    },
}
